
import java.io.*;
import java.nio.charset.Charset;
import java.nio.file.*;
import java.util.Arrays;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFileChooser;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author 789tyre (Gavin)
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        newEntry();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        entry = new javax.swing.JTextArea();
        saveB = new javax.swing.JButton();
        signInB = new javax.swing.JToggleButton();
        newEntryB = new javax.swing.JButton();
        fileName = new javax.swing.JLabel();
        loadB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        entry.setColumns(20);
        entry.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        entry.setLineWrap(true);
        entry.setRows(5);
        entry.setTabSize(4);
        entry.setWrapStyleWord(true);
        jScrollPane1.setViewportView(entry);

        saveB.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        saveB.setText("Save");
        saveB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBActionPerformed(evt);
            }
        });

        signInB.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        signInB.setText("Sign In");
        signInB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInBActionPerformed(evt);
            }
        });

        newEntryB.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        newEntryB.setText("New");
        newEntryB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newEntryBActionPerformed(evt);
            }
        });

        fileName.setFont(new java.awt.Font("Monospaced", 0, 20)); // NOI18N
        fileName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fileName.setText("Name of File here.md");
        fileName.setFocusable(false);
        fileName.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        loadB.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        loadB.setText("Load");
        loadB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fileName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(signInB)
                            .addComponent(loadB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newEntryB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(saveB, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {newEntryB, saveB});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fileName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(signInB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(loadB))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(newEntryB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveB))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void saveBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBActionPerformed
        //Spits out a brand new file name for each entry
        //String pathName = "entries/" + fileName.getText();

        Path path = Paths.get("entries/" + fileName.getText()); //Creates a path variable where we can save the md file
	Path folder = Paths.get("entries/");

        try {
            Files.createFile(path); // checks if the file exists and creates it if not there
            saveFile(path);
        } catch (FileAlreadyExistsException x) {

            try {
                saveFile(path); // Saves the text in the entry box
            } catch (IOException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }

        } catch (NoSuchFileException x) {

	    System.out.println("Cannot find the 'entries' folder. Creating one here");
	    //Create the entries folder then try to save the file again
	    try {
		Files.createDirectories(folder);
		saveFile(path);
	    } catch (IOException ex) {
		System.err.format("IOException %s%n", ex);
	    }

	} catch (IOException x) {
            System.err.format("createFile Error: %s%n", x);
        } 	

    }//GEN-LAST:event_saveBActionPerformed

    private void saveFile(Path path) throws IOException {
        //Will eventually save to Google Drive when there is internet.
        List<String> text = Arrays.asList(entry.getText().split("\\n"));
        Files.write(path, text, Charset.forName("UTF-8"));
    }

    private void newEntryBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newEntryBActionPerformed
        newEntry();
    }//GEN-LAST:event_newEntryBActionPerformed

    private void signInBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signInBActionPerformed

    private void loadBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadBActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        fc.setCurrentDirectory(new File("entries"));
        if (fc.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fc.getSelectedFile();
            loadFile(selectedFile.getName());
        }
        //loadFile("entry.md");
    }//GEN-LAST:event_loadBActionPerformed
    
    private void loadFile(String file){
        FileReader fr = null;
        BufferedReader br = null;
        List<String> text = new ArrayList<>();
        String entryTemp;
        
        try{
            fr = new FileReader("entries/" + file); //Navigates to the right directory (I plan on using only one)
            //fr = new FileReader(file);
            br  = new BufferedReader(fr);
            String currentLine = null;
            
            while ( (currentLine = br.readLine()) != null ){
                text.add(currentLine);
            }
            
        } catch (IOException e) {
            System.err.format("Error: %s%n", e);
            
        } finally {
            try{
                if (fr != null) {fr.close();}
                if (br != null) {br.close();}
            } catch (IOException e) {
                System.err.format("Error: %s%n", e);
            }
        }
        
        entryTemp = String.join("\n", text);
        fileName.setText(file);
        entry.setText(entryTemp);
    }
    
    private void newEntry() {
        //Puts the date into the first line of the entry box
        Date date = new Date();
        DateFormat dateformatFile = new SimpleDateFormat("yyyMMdd - HHmm");
        DateFormat dateformatEntry = new SimpleDateFormat("## *HH:mm @ dd/MM/yyyy*");
        
        fileName.setText( dateformatFile.format(date) + ".md" ); //Used for saving the entry
        entry.setText(dateformatEntry.format(date)); //Used to put in the actual entry
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Main().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea entry;
    private javax.swing.JLabel fileName;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton loadB;
    private javax.swing.JButton newEntryB;
    private javax.swing.JButton saveB;
    private javax.swing.JToggleButton signInB;
    // End of variables declaration//GEN-END:variables
}
